# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='user',
            name='isrobot',
            field=models.BooleanField(default=False),
        ),
    ]
