# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20171221_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isrobot',
            new_name='robot',
        ),
    ]
