# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20171221_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complimentor', models.ManyToManyField(related_name='compliments', to='login_reg.User')),
                ('favorite', models.ManyToManyField(related_name='favorited', to='login_reg.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallon',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='gallon',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Gallon',
        ),
    ]
